// This file is auto generated by script.js. DO NOT EDIT DIRECTLY!!!
export default {
  "ACADEMIC-CAP-OUTLINE": require<{
    default: string;
  }>("./files/outline/academic-cap.svg").default,
  "ADJUSTMENTS-OUTLINE": require<{
    default: string;
  }>("./files/outline/adjustments.svg").default,
  "ANNOTATION-OUTLINE": require<{
    default: string;
  }>("./files/outline/annotation.svg").default,
  "ARCHIVE-OUTLINE": require<{ default: string }>("./files/outline/archive.svg")
    .default,
  "ARROW-CIRCLE-DOWN-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-circle-down.svg").default,
  "ARROW-CIRCLE-LEFT-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-circle-left.svg").default,
  "ARROW-CIRCLE-RIGHT-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-circle-right.svg").default,
  "ARROW-CIRCLE-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-circle-up.svg").default,
  "ARROW-DOWN-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-down.svg").default,
  "ARROW-LEFT-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-left.svg").default,
  "ARROW-NARROW-DOWN-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-narrow-down.svg").default,
  "ARROW-NARROW-LEFT-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-narrow-left.svg").default,
  "ARROW-NARROW-RIGHT-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-narrow-right.svg").default,
  "ARROW-NARROW-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-narrow-up.svg").default,
  "ARROW-RIGHT-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-right.svg").default,
  "ARROW-SM-DOWN-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-sm-down.svg").default,
  "ARROW-SM-LEFT-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-sm-left.svg").default,
  "ARROW-SM-RIGHT-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-sm-right.svg").default,
  "ARROW-SM-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-sm-up.svg").default,
  "ARROW-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrow-up.svg").default,
  "ARROWS-EXPAND-OUTLINE": require<{
    default: string;
  }>("./files/outline/arrows-expand.svg").default,
  "AT-SYMBOL-OUTLINE": require<{
    default: string;
  }>("./files/outline/at-symbol.svg").default,
  "BACKSPACE-OUTLINE": require<{
    default: string;
  }>("./files/outline/backspace.svg").default,
  "BADGE-CHECK-OUTLINE": require<{
    default: string;
  }>("./files/outline/badge-check.svg").default,
  "BAN-OUTLINE": require<{ default: string }>("./files/outline/ban.svg")
    .default,
  "BEAKER-OUTLINE": require<{ default: string }>("./files/outline/beaker.svg")
    .default,
  "BELL-OUTLINE": require<{ default: string }>("./files/outline/bell.svg")
    .default,
  "BOOK-OPEN-OUTLINE": require<{
    default: string;
  }>("./files/outline/book-open.svg").default,
  "BOOKMARK-ALT-OUTLINE": require<{
    default: string;
  }>("./files/outline/bookmark-alt.svg").default,
  "BOOKMARK-OUTLINE": require<{
    default: string;
  }>("./files/outline/bookmark.svg").default,
  "BRIEFCASE-OUTLINE": require<{
    default: string;
  }>("./files/outline/briefcase.svg").default,
  "CAKE-OUTLINE": require<{ default: string }>("./files/outline/cake.svg")
    .default,
  "CALCULATOR-OUTLINE": require<{
    default: string;
  }>("./files/outline/calculator.svg").default,
  "CALENDAR-OUTLINE": require<{
    default: string;
  }>("./files/outline/calendar.svg").default,
  "CAMERA-OUTLINE": require<{ default: string }>("./files/outline/camera.svg")
    .default,
  "CASH-OUTLINE": require<{ default: string }>("./files/outline/cash.svg")
    .default,
  "CHART-BAR-OUTLINE": require<{
    default: string;
  }>("./files/outline/chart-bar.svg").default,
  "CHART-PIE-OUTLINE": require<{
    default: string;
  }>("./files/outline/chart-pie.svg").default,
  "CHART-SQUARE-BAR-OUTLINE": require<{
    default: string;
  }>("./files/outline/chart-square-bar.svg").default,
  "CHAT-ALT-2-OUTLINE": require<{
    default: string;
  }>("./files/outline/chat-alt-2.svg").default,
  "CHAT-ALT-OUTLINE": require<{
    default: string;
  }>("./files/outline/chat-alt.svg").default,
  "CHAT-OUTLINE": require<{ default: string }>("./files/outline/chat.svg")
    .default,
  "CHECK-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/check-circle.svg").default,
  "CHECK-OUTLINE": require<{ default: string }>("./files/outline/check.svg")
    .default,
  "CHEVRON-DOUBLE-DOWN-OUTLINE": require<{
    default: string;
  }>("./files/outline/chevron-double-down.svg").default,
  "CHEVRON-DOUBLE-LEFT-OUTLINE": require<{
    default: string;
  }>("./files/outline/chevron-double-left.svg").default,
  "CHEVRON-DOUBLE-RIGHT-OUTLINE": require<{
    default: string;
  }>("./files/outline/chevron-double-right.svg").default,
  "CHEVRON-DOUBLE-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/chevron-double-up.svg").default,
  "CHEVRON-DOWN-OUTLINE": require<{
    default: string;
  }>("./files/outline/chevron-down.svg").default,
  "CHEVRON-LEFT-OUTLINE": require<{
    default: string;
  }>("./files/outline/chevron-left.svg").default,
  "CHEVRON-RIGHT-OUTLINE": require<{
    default: string;
  }>("./files/outline/chevron-right.svg").default,
  "CHEVRON-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/chevron-up.svg").default,
  "CHIP-OUTLINE": require<{ default: string }>("./files/outline/chip.svg")
    .default,
  "CLIPBOARD-CHECK-OUTLINE": require<{
    default: string;
  }>("./files/outline/clipboard-check.svg").default,
  "CLIPBOARD-COPY-OUTLINE": require<{
    default: string;
  }>("./files/outline/clipboard-copy.svg").default,
  "CLIPBOARD-LIST-OUTLINE": require<{
    default: string;
  }>("./files/outline/clipboard-list.svg").default,
  "CLIPBOARD-OUTLINE": require<{
    default: string;
  }>("./files/outline/clipboard.svg").default,
  "CLOCK-OUTLINE": require<{ default: string }>("./files/outline/clock.svg")
    .default,
  "CLOUD-DOWNLOAD-OUTLINE": require<{
    default: string;
  }>("./files/outline/cloud-download.svg").default,
  "CLOUD-UPLOAD-OUTLINE": require<{
    default: string;
  }>("./files/outline/cloud-upload.svg").default,
  "CLOUD-OUTLINE": require<{ default: string }>("./files/outline/cloud.svg")
    .default,
  "CODE-OUTLINE": require<{ default: string }>("./files/outline/code.svg")
    .default,
  "COG-OUTLINE": require<{ default: string }>("./files/outline/cog.svg")
    .default,
  "COLLECTION-OUTLINE": require<{
    default: string;
  }>("./files/outline/collection.svg").default,
  "COLOR-SWATCH-OUTLINE": require<{
    default: string;
  }>("./files/outline/color-swatch.svg").default,
  "CREDIT-CARD-OUTLINE": require<{
    default: string;
  }>("./files/outline/credit-card.svg").default,
  "CUBE-TRANSPARENT-OUTLINE": require<{
    default: string;
  }>("./files/outline/cube-transparent.svg").default,
  "CUBE-OUTLINE": require<{ default: string }>("./files/outline/cube.svg")
    .default,
  "CURRENCY-BANGLADESHI-OUTLINE": require<{
    default: string;
  }>("./files/outline/currency-bangladeshi.svg").default,
  "CURRENCY-DOLLAR-OUTLINE": require<{
    default: string;
  }>("./files/outline/currency-dollar.svg").default,
  "CURRENCY-EURO-OUTLINE": require<{
    default: string;
  }>("./files/outline/currency-euro.svg").default,
  "CURRENCY-POUND-OUTLINE": require<{
    default: string;
  }>("./files/outline/currency-pound.svg").default,
  "CURRENCY-RUPEE-OUTLINE": require<{
    default: string;
  }>("./files/outline/currency-rupee.svg").default,
  "CURRENCY-YEN-OUTLINE": require<{
    default: string;
  }>("./files/outline/currency-yen.svg").default,
  "CURSOR-CLICK-OUTLINE": require<{
    default: string;
  }>("./files/outline/cursor-click.svg").default,
  "DATABASE-OUTLINE": require<{
    default: string;
  }>("./files/outline/database.svg").default,
  "DESKTOP-COMPUTER-OUTLINE": require<{
    default: string;
  }>("./files/outline/desktop-computer.svg").default,
  "DEVICE-MOBILE-OUTLINE": require<{
    default: string;
  }>("./files/outline/device-mobile.svg").default,
  "DEVICE-TABLET-OUTLINE": require<{
    default: string;
  }>("./files/outline/device-tablet.svg").default,
  "DOCUMENT-ADD-OUTLINE": require<{
    default: string;
  }>("./files/outline/document-add.svg").default,
  "DOCUMENT-DOWNLOAD-OUTLINE": require<{
    default: string;
  }>("./files/outline/document-download.svg").default,
  "DOCUMENT-DUPLICATE-OUTLINE": require<{
    default: string;
  }>("./files/outline/document-duplicate.svg").default,
  "DOCUMENT-REMOVE-OUTLINE": require<{
    default: string;
  }>("./files/outline/document-remove.svg").default,
  "DOCUMENT-REPORT-OUTLINE": require<{
    default: string;
  }>("./files/outline/document-report.svg").default,
  "DOCUMENT-SEARCH-OUTLINE": require<{
    default: string;
  }>("./files/outline/document-search.svg").default,
  "DOCUMENT-TEXT-OUTLINE": require<{
    default: string;
  }>("./files/outline/document-text.svg").default,
  "DOCUMENT-OUTLINE": require<{
    default: string;
  }>("./files/outline/document.svg").default,
  "DOTS-CIRCLE-HORIZONTAL-OUTLINE": require<{
    default: string;
  }>("./files/outline/dots-circle-horizontal.svg").default,
  "DOTS-HORIZONTAL-OUTLINE": require<{
    default: string;
  }>("./files/outline/dots-horizontal.svg").default,
  "DOTS-VERTICAL-OUTLINE": require<{
    default: string;
  }>("./files/outline/dots-vertical.svg").default,
  "DOWNLOAD-OUTLINE": require<{
    default: string;
  }>("./files/outline/download.svg").default,
  "DUPLICATE-OUTLINE": require<{
    default: string;
  }>("./files/outline/duplicate.svg").default,
  "EMOJI-HAPPY-OUTLINE": require<{
    default: string;
  }>("./files/outline/emoji-happy.svg").default,
  "EMOJI-SAD-OUTLINE": require<{
    default: string;
  }>("./files/outline/emoji-sad.svg").default,
  "EXCLAMATION-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/exclamation-circle.svg").default,
  "EXCLAMATION-OUTLINE": require<{
    default: string;
  }>("./files/outline/exclamation.svg").default,
  "EXTERNAL-LINK-OUTLINE": require<{
    default: string;
  }>("./files/outline/external-link.svg").default,
  "EYE-OFF-OUTLINE": require<{ default: string }>("./files/outline/eye-off.svg")
    .default,
  "EYE-OUTLINE": require<{ default: string }>("./files/outline/eye.svg")
    .default,
  "FAST-FORWARD-OUTLINE": require<{
    default: string;
  }>("./files/outline/fast-forward.svg").default,
  "FILM-OUTLINE": require<{ default: string }>("./files/outline/film.svg")
    .default,
  "FILTER-OUTLINE": require<{ default: string }>("./files/outline/filter.svg")
    .default,
  "FINGER-PRINT-OUTLINE": require<{
    default: string;
  }>("./files/outline/finger-print.svg").default,
  "FIRE-OUTLINE": require<{ default: string }>("./files/outline/fire.svg")
    .default,
  "FLAG-OUTLINE": require<{ default: string }>("./files/outline/flag.svg")
    .default,
  "FOLDER-ADD-OUTLINE": require<{
    default: string;
  }>("./files/outline/folder-add.svg").default,
  "FOLDER-DOWNLOAD-OUTLINE": require<{
    default: string;
  }>("./files/outline/folder-download.svg").default,
  "FOLDER-OPEN-OUTLINE": require<{
    default: string;
  }>("./files/outline/folder-open.svg").default,
  "FOLDER-REMOVE-OUTLINE": require<{
    default: string;
  }>("./files/outline/folder-remove.svg").default,
  "FOLDER-OUTLINE": require<{ default: string }>("./files/outline/folder.svg")
    .default,
  "GIFT-OUTLINE": require<{ default: string }>("./files/outline/gift.svg")
    .default,
  "GLOBE-ALT-OUTLINE": require<{
    default: string;
  }>("./files/outline/globe-alt.svg").default,
  "GLOBE-OUTLINE": require<{ default: string }>("./files/outline/globe.svg")
    .default,
  "HAND-OUTLINE": require<{ default: string }>("./files/outline/hand.svg")
    .default,
  "HASHTAG-OUTLINE": require<{ default: string }>("./files/outline/hashtag.svg")
    .default,
  "HEART-OUTLINE": require<{ default: string }>("./files/outline/heart.svg")
    .default,
  "HOME-OUTLINE": require<{ default: string }>("./files/outline/home.svg")
    .default,
  "IDENTIFICATION-OUTLINE": require<{
    default: string;
  }>("./files/outline/identification.svg").default,
  "INBOX-IN-OUTLINE": require<{
    default: string;
  }>("./files/outline/inbox-in.svg").default,
  "INBOX-OUTLINE": require<{ default: string }>("./files/outline/inbox.svg")
    .default,
  "INFORMATION-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/information-circle.svg").default,
  "KEY-OUTLINE": require<{ default: string }>("./files/outline/key.svg")
    .default,
  "LIBRARY-OUTLINE": require<{ default: string }>("./files/outline/library.svg")
    .default,
  "LIGHT-BULB-OUTLINE": require<{
    default: string;
  }>("./files/outline/light-bulb.svg").default,
  "LIGHTNING-BOLT-OUTLINE": require<{
    default: string;
  }>("./files/outline/lightning-bolt.svg").default,
  "LINK-OUTLINE": require<{ default: string }>("./files/outline/link.svg")
    .default,
  "LOCATION-MARKER-OUTLINE": require<{
    default: string;
  }>("./files/outline/location-marker.svg").default,
  "LOCK-CLOSED-OUTLINE": require<{
    default: string;
  }>("./files/outline/lock-closed.svg").default,
  "LOCK-OPEN-OUTLINE": require<{
    default: string;
  }>("./files/outline/lock-open.svg").default,
  "LOGIN-OUTLINE": require<{ default: string }>("./files/outline/login.svg")
    .default,
  "LOGOUT-OUTLINE": require<{ default: string }>("./files/outline/logout.svg")
    .default,
  "MAIL-OPEN-OUTLINE": require<{
    default: string;
  }>("./files/outline/mail-open.svg").default,
  "MAIL-OUTLINE": require<{ default: string }>("./files/outline/mail.svg")
    .default,
  "MAP-OUTLINE": require<{ default: string }>("./files/outline/map.svg")
    .default,
  "MENU-ALT-1-OUTLINE": require<{
    default: string;
  }>("./files/outline/menu-alt-1.svg").default,
  "MENU-ALT-2-OUTLINE": require<{
    default: string;
  }>("./files/outline/menu-alt-2.svg").default,
  "MENU-ALT-3-OUTLINE": require<{
    default: string;
  }>("./files/outline/menu-alt-3.svg").default,
  "MENU-ALT-4-OUTLINE": require<{
    default: string;
  }>("./files/outline/menu-alt-4.svg").default,
  "MENU-OUTLINE": require<{ default: string }>("./files/outline/menu.svg")
    .default,
  "MICROPHONE-OUTLINE": require<{
    default: string;
  }>("./files/outline/microphone.svg").default,
  "MINUS-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/minus-circle.svg").default,
  "MINUS-SM-OUTLINE": require<{
    default: string;
  }>("./files/outline/minus-sm.svg").default,
  "MINUS-OUTLINE": require<{ default: string }>("./files/outline/minus.svg")
    .default,
  "MOON-OUTLINE": require<{ default: string }>("./files/outline/moon.svg")
    .default,
  "MUSIC-NOTE-OUTLINE": require<{
    default: string;
  }>("./files/outline/music-note.svg").default,
  "NEWSPAPER-OUTLINE": require<{
    default: string;
  }>("./files/outline/newspaper.svg").default,
  "OFFICE-BUILDING-OUTLINE": require<{
    default: string;
  }>("./files/outline/office-building.svg").default,
  "PAPER-AIRPLANE-OUTLINE": require<{
    default: string;
  }>("./files/outline/paper-airplane.svg").default,
  "PAPER-CLIP-OUTLINE": require<{
    default: string;
  }>("./files/outline/paper-clip.svg").default,
  "PAUSE-OUTLINE": require<{ default: string }>("./files/outline/pause.svg")
    .default,
  "PENCIL-ALT-OUTLINE": require<{
    default: string;
  }>("./files/outline/pencil-alt.svg").default,
  "PENCIL-OUTLINE": require<{ default: string }>("./files/outline/pencil.svg")
    .default,
  "PHONE-INCOMING-OUTLINE": require<{
    default: string;
  }>("./files/outline/phone-incoming.svg").default,
  "PHONE-MISSED-CALL-OUTLINE": require<{
    default: string;
  }>("./files/outline/phone-missed-call.svg").default,
  "PHONE-OUTGOING-OUTLINE": require<{
    default: string;
  }>("./files/outline/phone-outgoing.svg").default,
  "PHONE-OUTLINE": require<{ default: string }>("./files/outline/phone.svg")
    .default,
  "PHOTOGRAPH-OUTLINE": require<{
    default: string;
  }>("./files/outline/photograph.svg").default,
  "PLAY-OUTLINE": require<{ default: string }>("./files/outline/play.svg")
    .default,
  "PLUS-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/plus-circle.svg").default,
  "PLUS-SM-OUTLINE": require<{ default: string }>("./files/outline/plus-sm.svg")
    .default,
  "PLUS-OUTLINE": require<{ default: string }>("./files/outline/plus.svg")
    .default,
  "PRESENTATION-CHART-BAR-OUTLINE": require<{
    default: string;
  }>("./files/outline/presentation-chart-bar.svg").default,
  "PRESENTATION-CHART-LINE-OUTLINE": require<{
    default: string;
  }>("./files/outline/presentation-chart-line.svg").default,
  "PRINTER-OUTLINE": require<{ default: string }>("./files/outline/printer.svg")
    .default,
  "PUZZLE-OUTLINE": require<{ default: string }>("./files/outline/puzzle.svg")
    .default,
  "QRCODE-OUTLINE": require<{ default: string }>("./files/outline/qrcode.svg")
    .default,
  "QUESTION-MARK-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/question-mark-circle.svg").default,
  "RECEIPT-REFUND-OUTLINE": require<{
    default: string;
  }>("./files/outline/receipt-refund.svg").default,
  "RECEIPT-TAX-OUTLINE": require<{
    default: string;
  }>("./files/outline/receipt-tax.svg").default,
  "REFRESH-OUTLINE": require<{ default: string }>("./files/outline/refresh.svg")
    .default,
  "REPLY-OUTLINE": require<{ default: string }>("./files/outline/reply.svg")
    .default,
  "REWIND-OUTLINE": require<{ default: string }>("./files/outline/rewind.svg")
    .default,
  "RSS-OUTLINE": require<{ default: string }>("./files/outline/rss.svg")
    .default,
  "SAVE-AS-OUTLINE": require<{ default: string }>("./files/outline/save-as.svg")
    .default,
  "SAVE-OUTLINE": require<{ default: string }>("./files/outline/save.svg")
    .default,
  "SCALE-OUTLINE": require<{ default: string }>("./files/outline/scale.svg")
    .default,
  "SCISSORS-OUTLINE": require<{
    default: string;
  }>("./files/outline/scissors.svg").default,
  "SEARCH-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/search-circle.svg").default,
  "SEARCH-OUTLINE": require<{ default: string }>("./files/outline/search.svg")
    .default,
  "SELECTOR-OUTLINE": require<{
    default: string;
  }>("./files/outline/selector.svg").default,
  "SERVER-OUTLINE": require<{ default: string }>("./files/outline/server.svg")
    .default,
  "SHARE-OUTLINE": require<{ default: string }>("./files/outline/share.svg")
    .default,
  "SHIELD-CHECK-OUTLINE": require<{
    default: string;
  }>("./files/outline/shield-check.svg").default,
  "SHIELD-EXCLAMATION-OUTLINE": require<{
    default: string;
  }>("./files/outline/shield-exclamation.svg").default,
  "SHOPPING-BAG-OUTLINE": require<{
    default: string;
  }>("./files/outline/shopping-bag.svg").default,
  "SHOPPING-CART-OUTLINE": require<{
    default: string;
  }>("./files/outline/shopping-cart.svg").default,
  "SORT-ASCENDING-OUTLINE": require<{
    default: string;
  }>("./files/outline/sort-ascending.svg").default,
  "SORT-DESCENDING-OUTLINE": require<{
    default: string;
  }>("./files/outline/sort-descending.svg").default,
  "SPARKLES-OUTLINE": require<{
    default: string;
  }>("./files/outline/sparkles.svg").default,
  "SPEAKERPHONE-OUTLINE": require<{
    default: string;
  }>("./files/outline/speakerphone.svg").default,
  "STAR-OUTLINE": require<{ default: string }>("./files/outline/star.svg")
    .default,
  "STATUS-OFFLINE-OUTLINE": require<{
    default: string;
  }>("./files/outline/status-offline.svg").default,
  "STATUS-ONLINE-OUTLINE": require<{
    default: string;
  }>("./files/outline/status-online.svg").default,
  "STOP-OUTLINE": require<{ default: string }>("./files/outline/stop.svg")
    .default,
  "SUN-OUTLINE": require<{ default: string }>("./files/outline/sun.svg")
    .default,
  "SUPPORT-OUTLINE": require<{ default: string }>("./files/outline/support.svg")
    .default,
  "SWITCH-HORIZONTAL-OUTLINE": require<{
    default: string;
  }>("./files/outline/switch-horizontal.svg").default,
  "SWITCH-VERTICAL-OUTLINE": require<{
    default: string;
  }>("./files/outline/switch-vertical.svg").default,
  "TABLE-OUTLINE": require<{ default: string }>("./files/outline/table.svg")
    .default,
  "TAG-OUTLINE": require<{ default: string }>("./files/outline/tag.svg")
    .default,
  "TEMPLATE-OUTLINE": require<{
    default: string;
  }>("./files/outline/template.svg").default,
  "TERMINAL-OUTLINE": require<{
    default: string;
  }>("./files/outline/terminal.svg").default,
  "THUMB-DOWN-OUTLINE": require<{
    default: string;
  }>("./files/outline/thumb-down.svg").default,
  "THUMB-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/thumb-up.svg").default,
  "TICKET-OUTLINE": require<{ default: string }>("./files/outline/ticket.svg")
    .default,
  "TRANSLATE-OUTLINE": require<{
    default: string;
  }>("./files/outline/translate.svg").default,
  "TRASH-OUTLINE": require<{ default: string }>("./files/outline/trash.svg")
    .default,
  "TRENDING-DOWN-OUTLINE": require<{
    default: string;
  }>("./files/outline/trending-down.svg").default,
  "TRENDING-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/trending-up.svg").default,
  "TRUCK-OUTLINE": require<{ default: string }>("./files/outline/truck.svg")
    .default,
  "UPLOAD-OUTLINE": require<{ default: string }>("./files/outline/upload.svg")
    .default,
  "USER-ADD-OUTLINE": require<{
    default: string;
  }>("./files/outline/user-add.svg").default,
  "USER-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/user-circle.svg").default,
  "USER-GROUP-OUTLINE": require<{
    default: string;
  }>("./files/outline/user-group.svg").default,
  "USER-REMOVE-OUTLINE": require<{
    default: string;
  }>("./files/outline/user-remove.svg").default,
  "USER-OUTLINE": require<{ default: string }>("./files/outline/user.svg")
    .default,
  "USERS-OUTLINE": require<{ default: string }>("./files/outline/users.svg")
    .default,
  "VARIABLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/variable.svg").default,
  "VIDEO-CAMERA-OUTLINE": require<{
    default: string;
  }>("./files/outline/video-camera.svg").default,
  "VIEW-BOARDS-OUTLINE": require<{
    default: string;
  }>("./files/outline/view-boards.svg").default,
  "VIEW-GRID-ADD-OUTLINE": require<{
    default: string;
  }>("./files/outline/view-grid-add.svg").default,
  "VIEW-GRID-OUTLINE": require<{
    default: string;
  }>("./files/outline/view-grid.svg").default,
  "VIEW-LIST-OUTLINE": require<{
    default: string;
  }>("./files/outline/view-list.svg").default,
  "VOLUME-OFF-OUTLINE": require<{
    default: string;
  }>("./files/outline/volume-off.svg").default,
  "VOLUME-UP-OUTLINE": require<{
    default: string;
  }>("./files/outline/volume-up.svg").default,
  "WIFI-OUTLINE": require<{ default: string }>("./files/outline/wifi.svg")
    .default,
  "X-CIRCLE-OUTLINE": require<{
    default: string;
  }>("./files/outline/x-circle.svg").default,
  "X-OUTLINE": require<{ default: string }>("./files/outline/x.svg").default,
  "ZOOM-IN-OUTLINE": require<{ default: string }>("./files/outline/zoom-in.svg")
    .default,
  "ZOOM-OUT-OUTLINE": require<{
    default: string;
  }>("./files/outline/zoom-out.svg").default,

  "ACADEMIC-CAP-SOLID": require<{
    default: string;
  }>("./files/solid/academic-cap.svg").default,
  "ADJUSTMENTS-SOLID": require<{
    default: string;
  }>("./files/solid/adjustments.svg").default,
  "ANNOTATION-SOLID": require<{
    default: string;
  }>("./files/solid/annotation.svg").default,
  "ARCHIVE-SOLID": require<{ default: string }>("./files/solid/archive.svg")
    .default,
  "ARROW-CIRCLE-DOWN-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-circle-down.svg").default,
  "ARROW-CIRCLE-LEFT-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-circle-left.svg").default,
  "ARROW-CIRCLE-RIGHT-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-circle-right.svg").default,
  "ARROW-CIRCLE-UP-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-circle-up.svg").default,
  "ARROW-DOWN-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-down.svg").default,
  "ARROW-LEFT-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-left.svg").default,
  "ARROW-NARROW-DOWN-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-narrow-down.svg").default,
  "ARROW-NARROW-LEFT-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-narrow-left.svg").default,
  "ARROW-NARROW-RIGHT-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-narrow-right.svg").default,
  "ARROW-NARROW-UP-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-narrow-up.svg").default,
  "ARROW-RIGHT-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-right.svg").default,
  "ARROW-SM-DOWN-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-sm-down.svg").default,
  "ARROW-SM-LEFT-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-sm-left.svg").default,
  "ARROW-SM-RIGHT-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-sm-right.svg").default,
  "ARROW-SM-UP-SOLID": require<{
    default: string;
  }>("./files/solid/arrow-sm-up.svg").default,
  "ARROW-UP-SOLID": require<{ default: string }>("./files/solid/arrow-up.svg")
    .default,
  "ARROWS-EXPAND-SOLID": require<{
    default: string;
  }>("./files/solid/arrows-expand.svg").default,
  "AT-SYMBOL-SOLID": require<{ default: string }>("./files/solid/at-symbol.svg")
    .default,
  "BACKSPACE-SOLID": require<{ default: string }>("./files/solid/backspace.svg")
    .default,
  "BADGE-CHECK-SOLID": require<{
    default: string;
  }>("./files/solid/badge-check.svg").default,
  "BAN-SOLID": require<{ default: string }>("./files/solid/ban.svg").default,
  "BEAKER-SOLID": require<{ default: string }>("./files/solid/beaker.svg")
    .default,
  "BELL-SOLID": require<{ default: string }>("./files/solid/bell.svg").default,
  "BOOK-OPEN-SOLID": require<{ default: string }>("./files/solid/book-open.svg")
    .default,
  "BOOKMARK-ALT-SOLID": require<{
    default: string;
  }>("./files/solid/bookmark-alt.svg").default,
  "BOOKMARK-SOLID": require<{ default: string }>("./files/solid/bookmark.svg")
    .default,
  "BRIEFCASE-SOLID": require<{ default: string }>("./files/solid/briefcase.svg")
    .default,
  "CAKE-SOLID": require<{ default: string }>("./files/solid/cake.svg").default,
  "CALCULATOR-SOLID": require<{
    default: string;
  }>("./files/solid/calculator.svg").default,
  "CALENDAR-SOLID": require<{ default: string }>("./files/solid/calendar.svg")
    .default,
  "CAMERA-SOLID": require<{ default: string }>("./files/solid/camera.svg")
    .default,
  "CASH-SOLID": require<{ default: string }>("./files/solid/cash.svg").default,
  "CHART-BAR-SOLID": require<{ default: string }>("./files/solid/chart-bar.svg")
    .default,
  "CHART-PIE-SOLID": require<{ default: string }>("./files/solid/chart-pie.svg")
    .default,
  "CHART-SQUARE-BAR-SOLID": require<{
    default: string;
  }>("./files/solid/chart-square-bar.svg").default,
  "CHAT-ALT-2-SOLID": require<{
    default: string;
  }>("./files/solid/chat-alt-2.svg").default,
  "CHAT-ALT-SOLID": require<{ default: string }>("./files/solid/chat-alt.svg")
    .default,
  "CHAT-SOLID": require<{ default: string }>("./files/solid/chat.svg").default,
  "CHECK-CIRCLE-SOLID": require<{
    default: string;
  }>("./files/solid/check-circle.svg").default,
  "CHECK-SOLID": require<{ default: string }>("./files/solid/check.svg")
    .default,
  "CHEVRON-DOUBLE-DOWN-SOLID": require<{
    default: string;
  }>("./files/solid/chevron-double-down.svg").default,
  "CHEVRON-DOUBLE-LEFT-SOLID": require<{
    default: string;
  }>("./files/solid/chevron-double-left.svg").default,
  "CHEVRON-DOUBLE-RIGHT-SOLID": require<{
    default: string;
  }>("./files/solid/chevron-double-right.svg").default,
  "CHEVRON-DOUBLE-UP-SOLID": require<{
    default: string;
  }>("./files/solid/chevron-double-up.svg").default,
  "CHEVRON-DOWN-SOLID": require<{
    default: string;
  }>("./files/solid/chevron-down.svg").default,
  "CHEVRON-LEFT-SOLID": require<{
    default: string;
  }>("./files/solid/chevron-left.svg").default,
  "CHEVRON-RIGHT-SOLID": require<{
    default: string;
  }>("./files/solid/chevron-right.svg").default,
  "CHEVRON-UP-SOLID": require<{
    default: string;
  }>("./files/solid/chevron-up.svg").default,
  "CHIP-SOLID": require<{ default: string }>("./files/solid/chip.svg").default,
  "CLIPBOARD-CHECK-SOLID": require<{
    default: string;
  }>("./files/solid/clipboard-check.svg").default,
  "CLIPBOARD-COPY-SOLID": require<{
    default: string;
  }>("./files/solid/clipboard-copy.svg").default,
  "CLIPBOARD-LIST-SOLID": require<{
    default: string;
  }>("./files/solid/clipboard-list.svg").default,
  "CLIPBOARD-SOLID": require<{ default: string }>("./files/solid/clipboard.svg")
    .default,
  "CLOCK-SOLID": require<{ default: string }>("./files/solid/clock.svg")
    .default,
  "CLOUD-DOWNLOAD-SOLID": require<{
    default: string;
  }>("./files/solid/cloud-download.svg").default,
  "CLOUD-UPLOAD-SOLID": require<{
    default: string;
  }>("./files/solid/cloud-upload.svg").default,
  "CLOUD-SOLID": require<{ default: string }>("./files/solid/cloud.svg")
    .default,
  "CODE-SOLID": require<{ default: string }>("./files/solid/code.svg").default,
  "COG-SOLID": require<{ default: string }>("./files/solid/cog.svg").default,
  "COLLECTION-SOLID": require<{
    default: string;
  }>("./files/solid/collection.svg").default,
  "COLOR-SWATCH-SOLID": require<{
    default: string;
  }>("./files/solid/color-swatch.svg").default,
  "CREDIT-CARD-SOLID": require<{
    default: string;
  }>("./files/solid/credit-card.svg").default,
  "CUBE-TRANSPARENT-SOLID": require<{
    default: string;
  }>("./files/solid/cube-transparent.svg").default,
  "CUBE-SOLID": require<{ default: string }>("./files/solid/cube.svg").default,
  "CURRENCY-BANGLADESHI-SOLID": require<{
    default: string;
  }>("./files/solid/currency-bangladeshi.svg").default,
  "CURRENCY-DOLLAR-SOLID": require<{
    default: string;
  }>("./files/solid/currency-dollar.svg").default,
  "CURRENCY-EURO-SOLID": require<{
    default: string;
  }>("./files/solid/currency-euro.svg").default,
  "CURRENCY-POUND-SOLID": require<{
    default: string;
  }>("./files/solid/currency-pound.svg").default,
  "CURRENCY-RUPEE-SOLID": require<{
    default: string;
  }>("./files/solid/currency-rupee.svg").default,
  "CURRENCY-YEN-SOLID": require<{
    default: string;
  }>("./files/solid/currency-yen.svg").default,
  "CURSOR-CLICK-SOLID": require<{
    default: string;
  }>("./files/solid/cursor-click.svg").default,
  "DATABASE-SOLID": require<{ default: string }>("./files/solid/database.svg")
    .default,
  "DESKTOP-COMPUTER-SOLID": require<{
    default: string;
  }>("./files/solid/desktop-computer.svg").default,
  "DEVICE-MOBILE-SOLID": require<{
    default: string;
  }>("./files/solid/device-mobile.svg").default,
  "DEVICE-TABLET-SOLID": require<{
    default: string;
  }>("./files/solid/device-tablet.svg").default,
  "DOCUMENT-ADD-SOLID": require<{
    default: string;
  }>("./files/solid/document-add.svg").default,
  "DOCUMENT-DOWNLOAD-SOLID": require<{
    default: string;
  }>("./files/solid/document-download.svg").default,
  "DOCUMENT-DUPLICATE-SOLID": require<{
    default: string;
  }>("./files/solid/document-duplicate.svg").default,
  "DOCUMENT-REMOVE-SOLID": require<{
    default: string;
  }>("./files/solid/document-remove.svg").default,
  "DOCUMENT-REPORT-SOLID": require<{
    default: string;
  }>("./files/solid/document-report.svg").default,
  "DOCUMENT-SEARCH-SOLID": require<{
    default: string;
  }>("./files/solid/document-search.svg").default,
  "DOCUMENT-TEXT-SOLID": require<{
    default: string;
  }>("./files/solid/document-text.svg").default,
  "DOCUMENT-SOLID": require<{ default: string }>("./files/solid/document.svg")
    .default,
  "DOTS-CIRCLE-HORIZONTAL-SOLID": require<{
    default: string;
  }>("./files/solid/dots-circle-horizontal.svg").default,
  "DOTS-HORIZONTAL-SOLID": require<{
    default: string;
  }>("./files/solid/dots-horizontal.svg").default,
  "DOTS-VERTICAL-SOLID": require<{
    default: string;
  }>("./files/solid/dots-vertical.svg").default,
  "DOWNLOAD-SOLID": require<{ default: string }>("./files/solid/download.svg")
    .default,
  "DUPLICATE-SOLID": require<{ default: string }>("./files/solid/duplicate.svg")
    .default,
  "EMOJI-HAPPY-SOLID": require<{
    default: string;
  }>("./files/solid/emoji-happy.svg").default,
  "EMOJI-SAD-SOLID": require<{ default: string }>("./files/solid/emoji-sad.svg")
    .default,
  "EXCLAMATION-CIRCLE-SOLID": require<{
    default: string;
  }>("./files/solid/exclamation-circle.svg").default,
  "EXCLAMATION-SOLID": require<{
    default: string;
  }>("./files/solid/exclamation.svg").default,
  "EXTERNAL-LINK-SOLID": require<{
    default: string;
  }>("./files/solid/external-link.svg").default,
  "EYE-OFF-SOLID": require<{ default: string }>("./files/solid/eye-off.svg")
    .default,
  "EYE-SOLID": require<{ default: string }>("./files/solid/eye.svg").default,
  "FAST-FORWARD-SOLID": require<{
    default: string;
  }>("./files/solid/fast-forward.svg").default,
  "FILM-SOLID": require<{ default: string }>("./files/solid/film.svg").default,
  "FILTER-SOLID": require<{ default: string }>("./files/solid/filter.svg")
    .default,
  "FINGER-PRINT-SOLID": require<{
    default: string;
  }>("./files/solid/finger-print.svg").default,
  "FIRE-SOLID": require<{ default: string }>("./files/solid/fire.svg").default,
  "FLAG-SOLID": require<{ default: string }>("./files/solid/flag.svg").default,
  "FOLDER-ADD-SOLID": require<{
    default: string;
  }>("./files/solid/folder-add.svg").default,
  "FOLDER-DOWNLOAD-SOLID": require<{
    default: string;
  }>("./files/solid/folder-download.svg").default,
  "FOLDER-OPEN-SOLID": require<{
    default: string;
  }>("./files/solid/folder-open.svg").default,
  "FOLDER-REMOVE-SOLID": require<{
    default: string;
  }>("./files/solid/folder-remove.svg").default,
  "FOLDER-SOLID": require<{ default: string }>("./files/solid/folder.svg")
    .default,
  "GIFT-SOLID": require<{ default: string }>("./files/solid/gift.svg").default,
  "GLOBE-ALT-SOLID": require<{ default: string }>("./files/solid/globe-alt.svg")
    .default,
  "GLOBE-SOLID": require<{ default: string }>("./files/solid/globe.svg")
    .default,
  "HAND-SOLID": require<{ default: string }>("./files/solid/hand.svg").default,
  "HASHTAG-SOLID": require<{ default: string }>("./files/solid/hashtag.svg")
    .default,
  "HEART-SOLID": require<{ default: string }>("./files/solid/heart.svg")
    .default,
  "HOME-SOLID": require<{ default: string }>("./files/solid/home.svg").default,
  "IDENTIFICATION-SOLID": require<{
    default: string;
  }>("./files/solid/identification.svg").default,
  "INBOX-IN-SOLID": require<{ default: string }>("./files/solid/inbox-in.svg")
    .default,
  "INBOX-SOLID": require<{ default: string }>("./files/solid/inbox.svg")
    .default,
  "INFORMATION-CIRCLE-SOLID": require<{
    default: string;
  }>("./files/solid/information-circle.svg").default,
  "KEY-SOLID": require<{ default: string }>("./files/solid/key.svg").default,
  "LIBRARY-SOLID": require<{ default: string }>("./files/solid/library.svg")
    .default,
  "LIGHT-BULB-SOLID": require<{
    default: string;
  }>("./files/solid/light-bulb.svg").default,
  "LIGHTNING-BOLT-SOLID": require<{
    default: string;
  }>("./files/solid/lightning-bolt.svg").default,
  "LINK-SOLID": require<{ default: string }>("./files/solid/link.svg").default,
  "LOCATION-MARKER-SOLID": require<{
    default: string;
  }>("./files/solid/location-marker.svg").default,
  "LOCK-CLOSED-SOLID": require<{
    default: string;
  }>("./files/solid/lock-closed.svg").default,
  "LOCK-OPEN-SOLID": require<{ default: string }>("./files/solid/lock-open.svg")
    .default,
  "LOGIN-SOLID": require<{ default: string }>("./files/solid/login.svg")
    .default,
  "LOGOUT-SOLID": require<{ default: string }>("./files/solid/logout.svg")
    .default,
  "MAIL-OPEN-SOLID": require<{ default: string }>("./files/solid/mail-open.svg")
    .default,
  "MAIL-SOLID": require<{ default: string }>("./files/solid/mail.svg").default,
  "MAP-SOLID": require<{ default: string }>("./files/solid/map.svg").default,
  "MENU-ALT-1-SOLID": require<{
    default: string;
  }>("./files/solid/menu-alt-1.svg").default,
  "MENU-ALT-2-SOLID": require<{
    default: string;
  }>("./files/solid/menu-alt-2.svg").default,
  "MENU-ALT-3-SOLID": require<{
    default: string;
  }>("./files/solid/menu-alt-3.svg").default,
  "MENU-ALT-4-SOLID": require<{
    default: string;
  }>("./files/solid/menu-alt-4.svg").default,
  "MENU-SOLID": require<{ default: string }>("./files/solid/menu.svg").default,
  "MICROPHONE-SOLID": require<{
    default: string;
  }>("./files/solid/microphone.svg").default,
  "MINUS-CIRCLE-SOLID": require<{
    default: string;
  }>("./files/solid/minus-circle.svg").default,
  "MINUS-SM-SOLID": require<{ default: string }>("./files/solid/minus-sm.svg")
    .default,
  "MINUS-SOLID": require<{ default: string }>("./files/solid/minus.svg")
    .default,
  "MOON-SOLID": require<{ default: string }>("./files/solid/moon.svg").default,
  "MUSIC-NOTE-SOLID": require<{
    default: string;
  }>("./files/solid/music-note.svg").default,
  "NEWSPAPER-SOLID": require<{ default: string }>("./files/solid/newspaper.svg")
    .default,
  "OFFICE-BUILDING-SOLID": require<{
    default: string;
  }>("./files/solid/office-building.svg").default,
  "PAPER-AIRPLANE-SOLID": require<{
    default: string;
  }>("./files/solid/paper-airplane.svg").default,
  "PAPER-CLIP-SOLID": require<{
    default: string;
  }>("./files/solid/paper-clip.svg").default,
  "PAUSE-SOLID": require<{ default: string }>("./files/solid/pause.svg")
    .default,
  "PENCIL-ALT-SOLID": require<{
    default: string;
  }>("./files/solid/pencil-alt.svg").default,
  "PENCIL-SOLID": require<{ default: string }>("./files/solid/pencil.svg")
    .default,
  "PHONE-INCOMING-SOLID": require<{
    default: string;
  }>("./files/solid/phone-incoming.svg").default,
  "PHONE-MISSED-CALL-SOLID": require<{
    default: string;
  }>("./files/solid/phone-missed-call.svg").default,
  "PHONE-OUTGOING-SOLID": require<{
    default: string;
  }>("./files/solid/phone-outgoing.svg").default,
  "PHONE-SOLID": require<{ default: string }>("./files/solid/phone.svg")
    .default,
  "PHOTOGRAPH-SOLID": require<{
    default: string;
  }>("./files/solid/photograph.svg").default,
  "PLAY-SOLID": require<{ default: string }>("./files/solid/play.svg").default,
  "PLUS-CIRCLE-SOLID": require<{
    default: string;
  }>("./files/solid/plus-circle.svg").default,
  "PLUS-SM-SOLID": require<{ default: string }>("./files/solid/plus-sm.svg")
    .default,
  "PLUS-SOLID": require<{ default: string }>("./files/solid/plus.svg").default,
  "PRESENTATION-CHART-BAR-SOLID": require<{
    default: string;
  }>("./files/solid/presentation-chart-bar.svg").default,
  "PRESENTATION-CHART-LINE-SOLID": require<{
    default: string;
  }>("./files/solid/presentation-chart-line.svg").default,
  "PRINTER-SOLID": require<{ default: string }>("./files/solid/printer.svg")
    .default,
  "PUZZLE-SOLID": require<{ default: string }>("./files/solid/puzzle.svg")
    .default,
  "QRCODE-SOLID": require<{ default: string }>("./files/solid/qrcode.svg")
    .default,
  "QUESTION-MARK-CIRCLE-SOLID": require<{
    default: string;
  }>("./files/solid/question-mark-circle.svg").default,
  "RECEIPT-REFUND-SOLID": require<{
    default: string;
  }>("./files/solid/receipt-refund.svg").default,
  "RECEIPT-TAX-SOLID": require<{
    default: string;
  }>("./files/solid/receipt-tax.svg").default,
  "REFRESH-SOLID": require<{ default: string }>("./files/solid/refresh.svg")
    .default,
  "REPLY-SOLID": require<{ default: string }>("./files/solid/reply.svg")
    .default,
  "REWIND-SOLID": require<{ default: string }>("./files/solid/rewind.svg")
    .default,
  "RSS-SOLID": require<{ default: string }>("./files/solid/rss.svg").default,
  "SAVE-AS-SOLID": require<{ default: string }>("./files/solid/save-as.svg")
    .default,
  "SAVE-SOLID": require<{ default: string }>("./files/solid/save.svg").default,
  "SCALE-SOLID": require<{ default: string }>("./files/solid/scale.svg")
    .default,
  "SCISSORS-SOLID": require<{ default: string }>("./files/solid/scissors.svg")
    .default,
  "SEARCH-CIRCLE-SOLID": require<{
    default: string;
  }>("./files/solid/search-circle.svg").default,
  "SEARCH-SOLID": require<{ default: string }>("./files/solid/search.svg")
    .default,
  "SELECTOR-SOLID": require<{ default: string }>("./files/solid/selector.svg")
    .default,
  "SERVER-SOLID": require<{ default: string }>("./files/solid/server.svg")
    .default,
  "SHARE-SOLID": require<{ default: string }>("./files/solid/share.svg")
    .default,
  "SHIELD-CHECK-SOLID": require<{
    default: string;
  }>("./files/solid/shield-check.svg").default,
  "SHIELD-EXCLAMATION-SOLID": require<{
    default: string;
  }>("./files/solid/shield-exclamation.svg").default,
  "SHOPPING-BAG-SOLID": require<{
    default: string;
  }>("./files/solid/shopping-bag.svg").default,
  "SHOPPING-CART-SOLID": require<{
    default: string;
  }>("./files/solid/shopping-cart.svg").default,
  "SORT-ASCENDING-SOLID": require<{
    default: string;
  }>("./files/solid/sort-ascending.svg").default,
  "SORT-DESCENDING-SOLID": require<{
    default: string;
  }>("./files/solid/sort-descending.svg").default,
  "SPARKLES-SOLID": require<{ default: string }>("./files/solid/sparkles.svg")
    .default,
  "SPEAKERPHONE-SOLID": require<{
    default: string;
  }>("./files/solid/speakerphone.svg").default,
  "STAR-SOLID": require<{ default: string }>("./files/solid/star.svg").default,
  "STATUS-OFFLINE-SOLID": require<{
    default: string;
  }>("./files/solid/status-offline.svg").default,
  "STATUS-ONLINE-SOLID": require<{
    default: string;
  }>("./files/solid/status-online.svg").default,
  "STOP-SOLID": require<{ default: string }>("./files/solid/stop.svg").default,
  "SUN-SOLID": require<{ default: string }>("./files/solid/sun.svg").default,
  "SUPPORT-SOLID": require<{ default: string }>("./files/solid/support.svg")
    .default,
  "SWITCH-HORIZONTAL-SOLID": require<{
    default: string;
  }>("./files/solid/switch-horizontal.svg").default,
  "SWITCH-VERTICAL-SOLID": require<{
    default: string;
  }>("./files/solid/switch-vertical.svg").default,
  "TABLE-SOLID": require<{ default: string }>("./files/solid/table.svg")
    .default,
  "TAG-SOLID": require<{ default: string }>("./files/solid/tag.svg").default,
  "TEMPLATE-SOLID": require<{ default: string }>("./files/solid/template.svg")
    .default,
  "TERMINAL-SOLID": require<{ default: string }>("./files/solid/terminal.svg")
    .default,
  "THUMB-DOWN-SOLID": require<{
    default: string;
  }>("./files/solid/thumb-down.svg").default,
  "THUMB-UP-SOLID": require<{ default: string }>("./files/solid/thumb-up.svg")
    .default,
  "TICKET-SOLID": require<{ default: string }>("./files/solid/ticket.svg")
    .default,
  "TRANSLATE-SOLID": require<{ default: string }>("./files/solid/translate.svg")
    .default,
  "TRASH-SOLID": require<{ default: string }>("./files/solid/trash.svg")
    .default,
  "TRENDING-DOWN-SOLID": require<{
    default: string;
  }>("./files/solid/trending-down.svg").default,
  "TRENDING-UP-SOLID": require<{
    default: string;
  }>("./files/solid/trending-up.svg").default,
  "TRUCK-SOLID": require<{ default: string }>("./files/solid/truck.svg")
    .default,
  "UPLOAD-SOLID": require<{ default: string }>("./files/solid/upload.svg")
    .default,
  "USER-ADD-SOLID": require<{ default: string }>("./files/solid/user-add.svg")
    .default,
  "USER-CIRCLE-SOLID": require<{
    default: string;
  }>("./files/solid/user-circle.svg").default,
  "USER-GROUP-SOLID": require<{
    default: string;
  }>("./files/solid/user-group.svg").default,
  "USER-REMOVE-SOLID": require<{
    default: string;
  }>("./files/solid/user-remove.svg").default,
  "USER-SOLID": require<{ default: string }>("./files/solid/user.svg").default,
  "USERS-SOLID": require<{ default: string }>("./files/solid/users.svg")
    .default,
  "VARIABLE-SOLID": require<{ default: string }>("./files/solid/variable.svg")
    .default,
  "VIDEO-CAMERA-SOLID": require<{
    default: string;
  }>("./files/solid/video-camera.svg").default,
  "VIEW-BOARDS-SOLID": require<{
    default: string;
  }>("./files/solid/view-boards.svg").default,
  "VIEW-GRID-ADD-SOLID": require<{
    default: string;
  }>("./files/solid/view-grid-add.svg").default,
  "VIEW-GRID-SOLID": require<{ default: string }>("./files/solid/view-grid.svg")
    .default,
  "VIEW-LIST-SOLID": require<{ default: string }>("./files/solid/view-list.svg")
    .default,
  "VOLUME-OFF-SOLID": require<{
    default: string;
  }>("./files/solid/volume-off.svg").default,
  "VOLUME-UP-SOLID": require<{ default: string }>("./files/solid/volume-up.svg")
    .default,
  "WIFI-SOLID": require<{ default: string }>("./files/solid/wifi.svg").default,
  "X-CIRCLE-SOLID": require<{ default: string }>("./files/solid/x-circle.svg")
    .default,
  "X-SOLID": require<{ default: string }>("./files/solid/x.svg").default,
  "ZOOM-IN-SOLID": require<{ default: string }>("./files/solid/zoom-in.svg")
    .default,
  "ZOOM-OUT-SOLID": require<{ default: string }>("./files/solid/zoom-out.svg")
    .default,
} as const;
