name: dev-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dev-test:
    runs-on: ubuntu-latest
    env:
      TEST_ENDPOINT: ui.test.onekey.so
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
          always-auth: true
          scope: "@onekeyhq"
          node-version: "14.x"
      - name: Install Dependiences
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
      - name: Build Target
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096" && yarn build-storybook
      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          cname: ${{ env.TEST_ENDPOINT }}
          force_orphan: true
      - name: Comment on PR
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: actions/github-script@v3
        env:
          SHA: ${{ github.sha }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `👋 Successfully deployed the latest commit \`${process.env.SHA}\` to https://${process.env.TEST_ENDPOINT}`
            })
